function aa(b,e,f,m,h){function r(){try{if(!y||0==y.length)return"";for(var a=y.length,c=Math.max.apply(null,y),d=Math.min.apply(null,y),g=0,b=0;b<a;b++)g+=y[b];return"&dvp_numts="+a+"&dvp_maxts="+c+"&dvp_mints="+d+"&dvp_avgts="+Math.round(g/a)}catch(n){return""}}function l(a,c){x=x.replace(ca[a],"&dbg"+a+"="+c)}function w(a,c){if(a instanceof Array){for(var d=0,g=a.length;d<g;d++)a[d]=a[d]+"="+c;return"&"+a.join("&")}return"&"+a+"="+c}var p=new J,t=h&&h.dvObj||window.$dv,k=h&&"undefined"!==typeof h.billable||
t&&t.tags[$uid]&&t.tags[$uid].billable,c=h&&h.impressionId||window.$uid,g=window.Yf||m,d=Array(g.lb),a=g.$a/g.gc+1,n=null,q="";b=b?b:null;f=f?f:"";var v="",z=null,D=0,Q=void 0,y=void 0,U=new RegExp(/&strp=[^&]*/),A=new RegExp(/&narme=[^&]*/),da=new RegExp(/&narm=[^&]*/),ea=new RegExp(/&naral=[^&]*/),fa=new RegExp(/&evid=[^&]*/);m=new RegExp(/&jsver=[^&]*/);for(var ga=new RegExp(/&vct=[^&]*/),ca=[new RegExp(/&dbg0=[^&]*/),new RegExp(/&dbg1=[^&]*/),new RegExp(/&dbg2=[^&]*/),new RegExp(/&dbg3=[^&]*/),
new RegExp(/&dbg4=[^&]*/),new RegExp(/&dbg5=[^&]*/),new RegExp(/&dbg6=[^&]*/),new RegExp(/&dbg7=[^&]*/),new RegExp(/&dbg8=[^&]*/),new RegExp(/&dbg9=[^&]*/),new RegExp(/&dbg10=[^&]*/),new RegExp(/&dbgtx=[^&]*/)],ha=[new RegExp(/&b0=[^&]*/),new RegExp(/&b1=[^&]*/),new RegExp(/&b2=[^&]*/),new RegExp(/&b3=[^&]*/),new RegExp(/&b4=[^&]*/),new RegExp(/&b5=[^&]*/),new RegExp(/&b6=[^&]*/),new RegExp(/&b7=[^&]*/),new RegExp(/&b8=[^&]*/),new RegExp(/&b9=[^&]*/),new RegExp(/&b10=[^&]*/),new RegExp(/&b11=[^&]*/)],
Y=Array(g.lb),u={fa:{D:null,F:null,A:null,v:null,Se:!1},j:{u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,Se:!1},za:{Cb:null,Bb:null},Jb:0},K="",L="",F,G,M="",N="",O=!1,H="",V=0;V<g.lb;V++)Y[V]="&b"+V+"=";e=function(a,c){if(a&&c)return c.replace(new RegExp(a+"=\\d*[&^#]"),"")}("prndr",e?e:null);var I=f+"?"+e,I=m.test(I)?I.replace(m,"&jsver="+b):I+"&jsver="+b,x="&naral=&narm=&narme=&dbg2=&dbg3=&dbg4=&dbg5=&dbg6=&dbg7=&dbg8=&dbg9=&dbg10=&dbgtx=&vct=",B="&strp=";e="&ctime="+(new Date).getTime();
var P=0,R="",S="",T=0,C=0,E=0,W=0;this.Yc=function(){return P};this.Pc=I+B+x+e+v+K;setEventId=function(a){z=a;x=x.replace(fa,"&evid="+z)};setAdLocatorIndicator=function(a){T=T|a;x=x.replace(ea,"&naral="+T)};setNAPMeasure=function(a){p.a("l2("+a+")");C=C|a;ia()?(setNotApplicableTime(),P=0):0==P&&(P=(new Date).getTime());x=x.replace(da,"&narm="+C);p.a("l2e")};setNAPMeasureErr=function(a){E=E|a;x=x.replace(A,"&narme="+E)};this.wd=function(a){W=W|a;x=x.replace(ga,"&vct="+W)};setBuckectStr=function(a,
c){c?v=v.replace(ha[a],"&b"+a+"="+d[a]):v=v+"&b"+a+"="+d[a]};setNotApplicableTime=function(){0!=P&&(R=(new Date).getTime()-P)};getBucketString=function(){return v};getFraudNonFraudEvents=function(a,c,d){return O?w(c,d):w(a,d)};this.rc=function(){return O};this.vd=function(a){n=a;B=B.replace(U,"&strp="+n);this.vd=function(){}};this.pb=function(){return(new Date).getTime()};var ja=this.pb();this.Ce=function(){return ja};this.Ef=function(){O=!0};this.Cf=function(a,c){H+="&"+c.reportQueryString.viewrate+
"="+a[c.serverProperties.viewedRate]+"&"+c.reportQueryString.error+"="+a[c.serverProperties.error]+"&"+c.reportQueryString.projected+"="+(1==a[c.serverProperties.viewed]?2:a[c.serverProperties.projected]);if("undefined"===typeof a[c.serverProperties.featurebit]||a[c.serverProperties.featurebit]&&1==a[c.serverProperties.featurebit])H+="&"+c.reportQueryString.measurems+"=0",1==a[c.serverProperties.viewed]&&(H+="&"+c.reportQueryString.viewedms+"=0")};this.pf=function(){C=C&-3;E=E&-2;E&=-3};this.Eb=function(){setNAPMeasure(2)};
this.Af=function(){setNAPMeasureErr(8);this.xc()};this.xc=function(){setNAPMeasure(4)};this.rd=function(){setAdLocatorIndicator(8);this.Eb()};this.Cd=function(a){setAdLocatorIndicator(16);l(9,a)};this.Dd=function(){setAdLocatorIndicator(1)};this.yf=function(){this.Eb();setNAPMeasureErr(1)};this.xf=function(){this.Eb();setNAPMeasureErr(2)};this.wc=function(a,c){setNAPMeasure(8);S=p.Wc(a,c)};this.uf=function(){p.a("l1");C=C&-3;setNAPMeasure(1);p.a("l1e")};this.ud=function(){setNAPMeasure(16)};this.te=
function(){return d};this.sd=function(b,n){c=c||h&&h.impressionId||window.$uid;var q;try{c&&t&&t.tags[c]&&t.tags[c].getTimeDiff&&(q=t.tags[c].getTimeDiff())}catch(k){}var f=q-Q||100;Q=q;y?200>y.length&&y.push(f):y=[];p.a("ie15");0<=b.i&&(q=Math.floor(b.i/g.gc),0<b.i%g.gc?q++:0<b.i&&q++,isNaN(d[q])&&(d[q]=0),d[q]+=Math.max(n,f),b.L&&q>=a||0==b.L&&6<=q?D+=Math.max(n,f):timeStampTotalBuckets=D=0);p.a("ie15e")};this.Ee=function(){for(var a=0,c=0;c<d.length;c++)d[c]&&(a+=d[c]);return a};this.wf=function(a){var c=
O?"false":a.fd;a="&advisonl="+(null==a.fd?"":c)+("&adabvvponl="+(null==a.ed?"":a.ed));l(8,"CSS1Compat"===document.compatMode?1:0);p.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&l(10,document.documentMode);p.a("ff52e");K=a};this.cb=function(a){p.a("ie14");N="&adbtftopg="+(null==a?"":O?"true":a)};this.vf=function(a){null!=a&&(u=a)};this.td=function(a){p.a("ie19");this.vf(a.G);this.Df();p.a("ie19e")};this.Gd=function(){var a;a="&vptoscrx="+(null!=u.fa.D?Math.round(u.fa.D):"");
a+="&vptoscry="+(null!=u.fa.F?Math.round(u.fa.F):"");a+="&vpwdth="+(null!=u.fa.A?Math.round(u.fa.A):"");a+="&vphgt="+(null!=u.fa.v?Math.round(u.fa.v):"");a+="&adtovpx="+(null!=u.j.u?Math.round(u.j.u):"");a+="&adtovpy="+(null!=u.j.s?Math.round(u.j.s):"");a+="&adtopgx="+(null!=u.j.H?Math.round(u.j.H):"");a+="&adtopgy="+(null!=u.j.I?Math.round(u.j.I):"");a+="&adtoscrx="+(null!=u.j.B?Math.round(u.j.B):"");a+="&adtoscry="+(null!=u.j.C?Math.round(u.j.C):"");a+="&scrwdth="+(null!=u.za.Cb?Math.round(u.za.Cb):
"");a+="&scrhgt="+(null!=u.za.Bb?Math.round(u.za.Bb):"");return a+="&almesind="+u.Jb};this.Hd=function(){var a="";if(F&&G){var c=null!=u.j.o?u.j.o:null,d=null!=u.j.m?u.j.m:null;0>F*G&&(a+="&dvp_adwdth="+F,a+="&dvp_adhgt="+G,F=c,G=d)}else F=null!=u.j.o?u.j.o:null,G=null!=u.j.m?u.j.m:null;a+="&adwdth="+(null!=F?F:"");return a+="&adhgt="+(null!=G?G:"")};this.Df=function(){setNotApplicableTime();v="";for(var a=0;a<d.length;a++)d[a]&&(v+=Y[a]+d[a]);L=this.Hd();M=K+this.Gd()+L;M+=N;this.Pc=I+B+x+v+M};this.Vc=
function(){return 1E3<=D};this.da=function(a){c=c||h&&h.impressionId||window.$uid;var d=I+"&impid="+c,g=-1,b=p.sb();try{t&&t.tags[c]&&t.tags[c].getTimeDiff&&(g=t.tags[c].getTimeDiff())}catch(n){}switch(a){case 1:q=g;d+=B+x+"&napt="+R+M+b+"&napr="+S;b="";k&&(b=h.Za?getFraudNonFraudEvents(["isbmms"],"isfbmms",g):getFraudNonFraudEvents(["isbmms","isgmmims"],"isfbmms",g));d+=b+getFraudNonFraudEvents("ismms","isfmms",g)+"&isumms="+g;break;case 2:d+=B+x+"&napt="+R+M+b+"&napr="+S+getFraudNonFraudEvents("isnmms",
"isfnmms",g);break;case 3:d+="&istoms="+g;case 4:case 8:d+=B+N+L+"&isbxdms="+g+(O?"&fbxdtb="+this.Ee():v)+r();break;case 5:q=q||g;d+=B+N+L+K+getFraudNonFraudEvents("isiabvms","isfiabvms",g)+"&isuiabvms="+g+getFraudNonFraudEvents("ismms","isfmms",q)+"&isumms="+q+r();break;case 6:q=q||g;d+=N+L+K+getFraudNonFraudEvents("iscvmvms","isfcvmvms",g)+getFraudNonFraudEvents("ismms","isfmms",q)+r();break;case 16:d+=B+x+"&napt="+R+b+"&napr="+S+"&ishems="+g;break;case 7:return d;case 9:d+=H;break;case 10:d+="&ismms=0";
break;case 17:q=q||g;b=h.Za?["isbmms"]:["isbmms","isgmmims"];d+=B+N+L+K+getFraudNonFraudEvents(h.Za?["isbvms"]:["isbvms","isgmpims"],"isfbvms",g)+getFraudNonFraudEvents(b,"isfbmms",q);break;default:d=this.Pc+"&napt="+R+"&ctime="+this.pb()+b+"&napr="+S}return d+"&evid="+a+"&ctime="+this.pb()};this.se=function(){p.a("ie17");for(var a=[],c=0;c<g.lb;c++)a[c]=d[c]?d[c]:0;return a};var ia=this.Zb=function(){return 2==(C&2)&&8!=(T&8)||4==(C&4)||8==(E&8)&&8==(T&8)?!1:!0};this.jf=function(a){p.a("l3");a=p.la(a);
p.a("cm3e");a&&(l(5,a.w),l(6,a.h));p.a("l3e")};return this}
function ba(b,e){this.window=null;this.nb={};this.images={};this.Hb=this.T=function(b){navigator.sendBeacon(b,{})};this.window=b;"function"!=typeof navigator.sendBeacon&&(this.bc=function(b){var e=this.window.document.createElement("img");e.name=e.id=b;e.width=0;e.height=0;e.style.display="none";e.src="";this.window.document.body.insertBefore(e,this.window.document.body.firstChild);return e},this.Hb=function(b,e){if(e&&1!=this.nb[e]||16==e)this.images[e]?(this.images[e].src=b,this.nb[e]=1):this.T(b,
e)},this.T=function(b,e){if(e&&1!=this.nb[e]||16==e||7==e)this.window.document.createElement("img").src=b,this.nb[e]=1},this.window&&(this.images={3:this.bc(e+"_13"),4:this.bc(e+"_14"),8:this.bc(e+"_18")}));return this}function X(){this.Hb=function(){};this.T=function(){}}
function ka(b,e,f,m){function h(){if(1==v){try{for(var a in n)q.removeChild(n[a]);d.document.body.removeChild(q)}catch(c){}v=!1}}function r(a){a=a||0;var c=p(0);c.jd()?7<c.rb()?(h(),D=z=v=!1):(v=!0,z=!1):20>a?(a++,setTimeout(r,50,a)):(v=z=D=!1,h())}function l(a){$dv&&$dv.tags&&$dv.tags[m]&&$dv.tags[m].getTimeDiff&&$dv.tags[m].getTimeDiff();if(null!==a.ib)for(var c=0;c<a.ib.length;c++){var d=p(c).rb();0==c?d>Q&&(Q=d):d>y&&(y=d)}}function w(a){for(var c=!0,d=0;13>=d;d++)var g=p(d),c=c&(null!==g&&g.jd());
if(!c)return null;a.Kc=0;a.uc=0;a.tc=0;a.oc=0;a.Ea=0;a.ib=Array(13);c=p(0).rb();for(d=1;13>=d;d++)if(g=5<Math.abs(p(d).rb()-c),a.ib[d]=g)switch(a.Kc++,d){case 2:case 3:case 4:case 5:a.uc++;break;case 6:case 7:case 8:case 9:a.tc++;break;case 10:case 11:case 12:case 13:a.oc++}if(13===a.Kc)return a.Ea=100,l(a),!0;c=a.ib;if(!1===c[1]){if(3<=a.oc||3<=a.tc||3<=a.uc)return l(a),null;a.Ea=0;l(a);return!1}if(!0===c[1]&&(!0===c[2]&&!0===c[3]||!0===c[2]&&!0===c[4]||!0===c[3]&&!0===c[5]||!0===c[4]&&!0===c[5])||
!0===c[1]&&4==a.tc||!0===c[1]&&4==a.oc&&1<=a.uc)return a.Ea=50,l(a),!0;if(c[2]&&c[5]&&!(c[6]&&c[10]&&c[1]&&c[13]&&c[9])||c[4]&&c[3]&&!(c[8]&&c[12]&&c[1]&&c[11]&&c[7]))return l(a),null;a.Ea=0;l(a);return!1}function p(a){a=n[a];var c=null;a&&(c=a.contentWindow);return c}function t(){for(var d=a.getBoundingClientRect(),g=d.width,b=d.height,q=g/(1+c),k=b/(1+c),e=g/c,t=b/c,v=0;13>=v;v++){var f=d.left,h=d.top;switch(v){case 0:h=f=-1E5;break;case 1:f+=(g-1)/2;h+=(b-1)/2;break;case 3:f+=g-1;break;case 4:h+=
b-1;break;case 5:f+=g-1;h+=b-1;break;case 6:f+=(g-e)/2;h+=(b-t)/2;break;case 7:f+=(g-e)/2+e;h+=(b-t)/2;break;case 8:f+=(g-e)/2;h+=(b-t)/2+t;break;case 9:f+=(g-e)/2+e;h+=(b-t)/2+t;break;case 10:f+=(g-q)/2;h+=(b-k)/2;break;case 11:f+=(g-q)/2+q;h+=(b-k)/2;break;case 12:f+=(g-q)/2;h+=(b-k)/2+k;break;case 13:f+=(g-q)/2+q,h+=(b-k)/2+k}6<=v&&(f-=.5,h-=.5);var z=n[v];z.style.left=f+"px";z.style.top=h+"px"}}function k(){if(null!=a&&null!=a.parentNode){z=!0;q=d.document.createElement("div");d.document.body.appendChild(q);
for(var c=0;13>=c;c++){var g=d.document.createElement("iframe");g.width=1;g.height=1;g.style.position="absolute";g.frameBorder="0";g.style.visibility="hidden";g.style.zIndex=-9999999;g.style.display="block";g.src="javascript:no=false;yes=true;("+function(){window.$e={ce:100};window.Sc=no;window.gb=0;window.Tc=0;window.dd=0;window.Zf=no;window.rb=function(){return window.dd};window.jd=function(){return window.Sc};window.Ye=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Yb=function(){window.gb++;window.Ye(window.Yb,document)};window.Yb();setInterval(function(){10>window.gb&&window.Yb();window.dd=window.gb-window.Tc;window.Tc=window.gb},window.$e.ce);window.setTimeout(function(){window.Sc=yes},250)}.toString()+")();";q.appendChild(g);n.push(g)}t()}}var c=Math.sqrt(2),g=new J,d=null,a=null,n=[],q,v=!1,z=!1,D=g.xb(b,e,f),Q=0,y=0;this.Oe=function(){0==z&&(0==(this.Ya()&&(null!=a&&g.hd(a,d)?!0:!1))?v=!1:(k(),r()))};this.Ya=function(){return D};
this.Ve=function(){return v};this.xd=function(c,g){d=c;a=g;this.Oe()};this.Ge=function(){if(0==v)return null;var a={};return null==w(a)?null:a.Ea}}
function la(b,e,f,m,h,r,l,w){this.b=new J;this.window=b;this.f=e;this.S=f;this.J=m;this.Y=l&&l.Enums.BrowserId||window.$dv.Enums.BrowserId;this.aa=l&&l.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.O=h;this.mc=r;this.ha=null;this.cd=this.window?this.b.yb(this.window.top):this.b.yb(window.top);this.Re=this.S!=this.aa.CrossDomain&&this.b.Va("ofs")&&this.cd;this.ha=new ka(this.S,this.J,l,w);null!=this.ha&&this.ha.Ya()&&this.ha.xd(this.window,this.f);this.tb=this.zb=this.sa=null;this.ub=
!1;var p=0;this.ja={Td:1,Ud:2,Nd:4,Pb:8,Md:16,Qb:32,Sd:64};this.vc=function(b,k,c,g){if(g&&g.insertBefore&&g.firstChild&&(b=this.window.document.createElement(b))){for(var d in k)b[d]=k[d];for(d in c)b.style[d]=c[d];g.insertBefore(b,g.firstChild);return b}return null};this.qe=function(b,k,c){var g=this.window.top,d=b.width,a=b.height;0>c.left?(d=b.width-Math.abs(c.left),0>k.Da&&(d-=Math.abs(k.Da))):0>k.Da&&(d=b.width-Math.abs(k.Da)+c.left,d=d>b.width?b.width:d);var n=b.width,q=Math.min(this.b.Ba(g.window).clientWidth,
g.innerWidth),e=screen.availWidth-q-k.Da,f=0;d<n?(n=d,f=q-d,0>k.Da&&(f-=Math.abs(k.Da))):f=q-n-c.left;0>f?(d=n-Math.abs(f),0>e&&(d-=Math.abs(e))):0>e&&(d=n-Math.abs(e)+f,d=d>n?n:d);k=screen.availHeight-k.qf-g.outerHeight;g=Math.min(this.b.Ba(g.window).clientHeight,g.innerHeight)-b.height-c.top;0>g?(a=b.height-Math.abs(g),0>k&&(a-=Math.abs(k))):0>k&&(a=b.height-Math.abs(k)+g,a=a>b.height?b.height:a);0>c.top&&(a-=Math.abs(c.top));return{Lf:d,Mf:a}};this.ic=function(b,k,c,g){var d=c.A,a=c.v,n=0;c=0;
var q={width:k.right-k.left,height:k.bottom-k.top};if(0>k.bottom||0>k.right||k.top>a||k.left>d||0>=q.width||0>=q.height)return 0;0>k.top?Math.abs(k.top)>=q.height?n=q.height:(n=q.height+k.top,n>a&&(n=a)):n=k.top+q.height>a?a-k.top:q.height;0>k.left?Math.abs(k.left)>=q.width?c=q.width:(c=q.width+k.left,c>d&&(c=d)):c=k.left+q.width>d?d-k.left:q.width;this.Re&&(b=this.qe(q,b,k),c=b.Lf,n=b.Mf);return 0>=c||0>=n?0:Math.round(c*n/(q.width*q.height)*(g?q.width*q.height/((g.right-g.left)*(g.bottom-g.top)):
1)*100)};this.hc=function(b,k){try{var c={x:b.offsetLeft,y:b.offsetTop};if(b.offsetParent){var g=this.hc(b.offsetParent,k);c.x+=g.x;c.y+=g.y}else k!=k.parent&&this.b.Rb(k,k.parent)&&(g=this.hc(k.frameElement,k.parent),c.x+=g.x,c.y+=g.y);return c}catch(d){return{x:null,y:null}}};this.pa=function(b){if(this.S==this.aa.CrossDomain)if(this.b.xa(this.window)&&this.window.$sf.ext.geom)this.pa=function(){var a=this.b.Ma(this.window),c=window.outerHeight||this.window.document.documentElement.clientHeight?
this.window.outerHeight-parseInt(a.win.h):this.O.Explorer.$,d={A:null,v:null,D:null,F:null,g:!1};d.A=parseInt(a.win.w);d.v=parseInt(a.win.h);d.D=parseInt(a.win.l);d.F=parseInt(a.win.t)+c;d.g=!0;return d};else if(this.J.X==this.Y.Firefox)this.pa=function(){var a=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,c=a?0:this.window.screenX-screen.left,a=a?0:this.window.screenY-screen.top,d={A:null,v:null,D:null,F:null,g:!1};d.A=this.window.outerWidth;d.v=this.window.outerHeight-this.O.Firefox.$;
d.D=c;d.F=a+this.O.Firefox.$;d.g=!0;return d};else if(this.b.qc(this.window)){var k=this;this.window.context.observeIntersection(function(a){a.forEach(function(a){k.sa=a})});this.pa=function(){var a={A:null,v:null,g:!1,D:null,F:null};null!=this.sa?(a.A=this.sa.rootBounds.width,a.v=this.sa.rootBounds.height):(a.A=0,a.v=0);a.g=!0;return a}}else if(this.J.X==this.Y.IE&&/^[11|12]/.test(this.J.wa))this.pa=function(){var a=-8==this.window.screenY&&-8==this.window.screenX,c=a?0:this.window.screenX,a=a?0:
this.window.screenY,d={A:null,v:null,D:null,F:null,g:!1};d.A=this.window.outerWidth;d.v=this.window.outerHeight-this.O.Explorer.$;d.D=c;d.F=a+this.O.Explorer.$;d.g=!0;return d};else if(this.J.X==this.Y.IE&&/[6-9]|[10]/.test(this.J.wa)){var c=this.vc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,le:0,af:"0",bf:"0"},{display:"inline",position:"absolute",top:0,left:0,Kf:"none",zIndex:0,border:0},this.window.document.body),g=this.vc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,le:0,
af:"0",bf:"0"},{display:"inline",position:"absolute",top:0,left:0,Kf:"none",zIndex:0,border:0},this.window.document.body),d=g.contentWindow||g.window||g.contentDocument.window||g.contentWindow.window||this.window.Pf,a=c.contentDocument||c.contentWindow.document,c=g.contentDocument||g.contentWindow.document,n="<html><head><script >window.onload = "+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.Ua={Ub:window.event.clientY,Tb:window.event.clientX,Fd:window.event.screenY-
window.event.clientY-window.screenY})}.toString()+"; \x3c/script></head><body></body></html>",g='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.ta={Ub:window.event.clientY,Tb:window.event.clientX,Ha:window.event.screenY-window.event.y,Ga:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";c.open("text/html",
"replace");c.write(g);c.close();a.open("text/html","replace");a.write(n);a.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.pa=function(){d.runMoM();a.open("text/html","replace");a.write(n);a.close();var c=this.window.ta,g=this.window.Ua,b=screen.availWidth,k=screen.availHeight,g=g?g.Fd:this.O.Explorer.$;if(c){var e=c.Ga,f=c.Ha;c.Ga>=b&&(c.Ga-=b);c.Ha>=k&&(c.Ha-=k);var h={A:null,v:null,D:null,F:null,g:!1};h.A=this.window.outerWidth?
this.window.outerWidth-20:b-c.Ga-20;h.v=this.window.outerHeight?this.window.outerHeight-g-10:k-c.Ha-10;h.D=e;h.F=f;h.g=!0}else h={A:null,v:null,D:null,F:null,g:!1},h.A=this.window.outerWidth?this.window.outerWidth-20:b-20,h.v=this.window.outerHeight?this.window.outerHeight-g-10:k-10,h.D=null,h.F=null,h.g=!1;return h}}else this.b.wb()?(this.pd(),this.pa=function(){this.ub||this.pd();var a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.O.Chrome.$;a.g=
!1;return a}):this.pa=this.J.X==this.Y.Chrome?function(){var a={A:null,v:null,D:null,F:null,g:!1},c=!1;try{a.A=this.window.frameElement.offsetParent.parentNode.clientWidth,a.v=this.window.frameElement.offsetParent.parentNode.clientHeight,c=!0}catch(d){}a.D=this.window.screenX;a.F=this.window.screenY;a.g=c;return a}:null!=this.ha&&this.ha.Ya()?function(){var a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.O.Safari.$;a.g=!1;return a}:function(){return{A:null,
v:null,D:null,F:null,g:!1}};else this.pa=function(){var a,c,d=this.window.top;void 0!=d.mozInnerScreenX&&null!=d.mozInnerScreenX?(a=d.mozInnerScreenX,c=d.mozInnerScreenY):void 0!=d.screenX&&null!=d.screenX?0!=d.screenLeft+8&&d.screenLeft+8!=screen.width||0!=d.screenTop+8&&d.screenTop+8!=screen.height?(a=d.screenLeft,c=d.screenTop+(d.outerHeight-d.innerHeight)):(a=d.screenLeft+8,c=d.screenTop+(d.outerHeight-d.innerHeight)+8):(a=d.screenLeft,c=d.screenTop);var g={A:null,v:null,D:null,F:null,g:!1},b=
this.b.Ba(d);g.A=d.innerWidth||b.clientWidth;g.v=d.innerHeight||b.clientHeight;g.D=a;g.F=c;g.g=!0;return g};return this.pa(b)};this.oa=function(b,k){p=1;this.S==this.aa.CrossDomain?this.b.xa(this.window)&&this.window.$sf.ext.geom&&this.b.Ma(this.window).par?(p=8,this.oa=function(){var c=this.b.Ma(this.window),g=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(c.win.h):this.O.Explorer.$,d={u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,
g:!1,rect:null,P:null,ra:null};d.u=parseInt(c.self.l)-parseInt(c.par.l);d.s=parseInt(c.self.t)-parseInt(c.par.t);d.H=parseInt(c.self.l);d.I=parseInt(c.self.t);d.B=parseInt(c.win.l)+d.u;d.C=parseInt(c.win.t)+d.s+g;d.o=parseInt(c.self.w);d.m=parseInt(c.self.h);d.g=!0;d.rect={top:d.s,bottom:d.s+d.m,left:d.u,right:d.u+d.o};return d}):this.J.X==this.Y.Firefox?this.oa=function(){var c=1;window.devicePixelRatio&&(c=window.devicePixelRatio);var g=this.window.screenX,d=this.window.screenY,a=this.window.mozInnerScreenX/
c-g,c=this.window.mozInnerScreenY/c-d-this.O.Firefox.$,a={left:a,top:c,right:a+this.window.innerWidth,bottom:c+this.window.innerHeight},c={u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null};c.u=a.left;c.s=a.top;c.H=null;c.I=null;c.B=g+a.left;c.C=d+a.top;c.o=this.window.innerWidth;c.m=this.window.innerHeight;c.g=!0;c.rect=a;this.b.Ib()&&(c=this.ob(c));return c}:this.b.qc(this.window)?(p=32,this.oa=function(){var c={u:null,s:null,o:null,m:null,g:!1,rect:null,P:null,
ra:null,H:null,I:null,B:null,C:null};null!=this.sa?(c.u=this.sa.boundingClientRect.left,c.s=this.sa.boundingClientRect.top,c.o=this.sa.boundingClientRect.width,c.m=this.sa.boundingClientRect.height):(c.u=0,c.s=0,c.o=0,c.m=0);c.g=!0;c.rect={top:c.s,bottom:c.s+c.m,left:c.u,right:c.u+c.o};return c}):this.J.X==this.Y.IE&&/^[11|12]/.test(this.J.wa)?this.oa=function(c){var g=this.window.screenLeft-window.screenX,d=this.window.screenTop-window.screenY-this.O.Explorer.$,g={left:g,top:d,right:g+this.window.innerWidth,
bottom:d+this.window.innerHeight},d={u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null};d.u=g.left;d.s=g.top;d.H=null;d.I=null;d.B=c.D+g.left;d.C=c.F+g.top;d.o=this.window.innerWidth;d.m=this.window.innerHeight;d.g=!0;d.rect=g;this.b.Ib()&&(d=this.ob(d));return d}:this.J.X==this.Y.IE&&/[6-9]|[10]/.test(this.J.wa)?this.oa=function(){if(8==document.documentMode)return{u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null};var c=this.window.Ua&&
this.window.ta?this.window.Ua.Ub-this.window.ta.Ub:0,g=this.window.Ua&&this.window.ta?this.window.Ua.Tb-this.window.ta.Tb:0,d=this.b.Ba(this.window),a={u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null};a.u=g;a.s=c;a.H=null;a.I=null;a.B=this.window.ta?g+this.window.ta.Ga:null;a.C=this.window.ta?c+this.window.ta.Ha:null;a.o=this.window.innerWidth||d.clientWidth;a.m=this.window.innerHeight||d.clientHeight;a.g=!0;a.rect={left:g,top:c,right:g+(this.window.innerWidth||
d.clientWidth),bottom:c+(this.window.innerHeight||d.clientHeight)};this.b.Ib()&&(a=this.ob(a));return a}:this.b.wb()?(p=512,this.oa=function(){var c={u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null};null!=this.f&&(adData=this.b.qb(this.f),c.o=adData?adData.w:this.window.innerWidth,c.m=adData?adData.h:this.window.innerHeight);return c}):this.oa=this.J.X==this.Y.Chrome?function(){var c=null,g=null,d=!1;try{var a=this.window.frameElement.offsetTop,c=this.window.frameElement.offsetLeft-
this.window.frameElement.offsetParent.scrollLeft,g=a-this.window.frameElement.offsetParent.scrollTop,d=!0}catch(b){}a={u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null};a.u=c;a.s=g;a.H=null;a.I=null;a.B=null;a.C=null;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.g=d;a.rect=d?{left:c,top:g,right:c+this.window.innerWidth,bottom:g+this.window.innerHeight}:null;this.b.Ib()&&(a=this.ob(a));return a}:null!=this.ha&&this.ha.Ya()?function(){var c={u:null,s:null,
H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null};null!=this.f&&(adData=this.b.qb(this.f),c.o=adData?adData.w:this.window.innerWidth,c.m=adData?adData.h:this.window.innerHeight);return c}:function(){return{u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null}}:this.oa=function(c){var g=this.hc(this.f,this.window),d={u:null,s:null,H:null,I:null,B:null,C:null,o:null,m:null,g:!1,rect:null,P:null,ra:null},a=this.b.jc(this.f,this.window),b=this.b.Dc(this.f,
this.window);d.u=b.left;d.s=b.top;d.H=g.x;d.I=g.y;d.B=c.D+b.left;d.C=c.F+b.top;d.o=b.w;d.m=b.h;d.g=!0;d.rect=a;d.P=b;return d};return this.oa(b,k)};this.ob=function(b){if(this.window.document.body==this.f||this.window.document.documentElement==this.f)return b;var k=this.b.qb(this.f);if(k){var c=k.w,g=k.h,d=b.u,a=b.s,n=b.C,e=b.B;null!=b.u&&null!=b.s&&null!=b.m&&null!=b.o&&b.rect&&(0<k.t?(a=b.s+k.t,null!=b.C&&(n=b.C+k.t)):g+=k.t,0<k.l?(d+=k.l,null!=b.B&&(e=b.B+k.l)):c+=k.l,k.r>b.o&&(c-=k.r-b.o),k.Jc>
b.m&&(g-=k.Jc-b.m),b.o=0<c?c:0,b.m=0<g?g:0,b.u=d,b.s=a,b.C=n,b.B=e,b.rect.left=b.u,b.rect.top=b.s,b.rect.right=b.u+k.w,b.rect.bottom=b.s+k.h,b.P={w:c,h:g,left:d,right:d+c,top:a,bottom:a+g})}return b};this.Be=function(){var b=screen.availWidth,k=screen.availHeight,c=screen.width,g=screen.height,d=0,a=0;this.cd&&(a=this.window.top,d=a.screenX,a=a.screenY);return{g:$dv.CommonData&&$dv.CommonData.deviceType&&1==$dv.CommonData.deviceType?"undefined"!==typeof d:!1,Cb:b||c,Bb:k||g,Wf:d,Xf:a,Da:d-(c-b),qf:a-
(g-k)}};this.oe=function(){var b=this.Be(),k=this.pa(b),c=this.oa(k,b);return{fa:k,j:c,za:b,Jb:(null==k.D||null==k.F?0:this.ja.Td)|(null==k.A||null==k.v?0:this.ja.Ud)|(null==c.u||null==c.s?0:this.ja.Nd)|(null==c.H||null==c.I?0:this.ja.Pb)|(null==c.B||null==c.C?0:this.ja.Md)|(null==c.m||null==c.o?0:this.ja.Qb)|(null==b.Bb||null==b.Cb?0:this.ja.Sd),L:this.Oc(c.m,c.o)}};this.Oc=function(b,k){null==b&&(b=0);null==k&&(k=0);return this.O.Ff&&242500<=b*k?!0:!1};this.we=function(){this.b.a("c10");if(null!=
this.f)if(this.b.hd(this.f,this.window))try{var b={timeStamp:new Date,i:-3,ka:-3,G:null,L:!1,ga:0};if(!this.mc())return b;var k=this.oe();if(!k.j.g||!k.fa.g){if(this.b.xa(this.window)&&this.window.$sf.ext.inViewPercentage){var c=this.window.$sf.ext.inViewPercentage();return{timeStamp:new Date,i:c,ka:c,G:k,L:k.L,ga:16}}if(this.b.wb()&&this.ub)return c=0,null!=this.tb&&(c=Math.round(100*this.tb.intersectionRatio)),{timeStamp:new Date,i:c,ka:c,G:k,L:this.Oc(k.j.m,k.j.o),ga:512};if(this.ha.Ya()){var g=
{timeStamp:new Date,i:-3,ka:-3,G:null,L:!1,ga:2};if(0==this.ha.Ve())g.i=-6,g.ka=-6,this.ha.xd(this.window,this.f);else{var d=this.ha.Ge();null!=d&&(g.G=k,g.L=k.L,g.i=d,g.ka=d)}return g}b.G=k;p&&(b.ga=p);return b}if(k.j&&k.j.P&&(0===k.j.P.w||1===k.j.P.w||0===k.j.P.h||1===k.j.P.h))return{timeStamp:new Date,i:-5,ka:-5,G:k,ga:p};c=k.j.P?this.ic(k.za,k.j.P,k.fa,k.j.rect):this.ic(k.za,k.j.rect,k.fa);return{timeStamp:new Date,i:c,ka:c,G:k,L:k.L,ga:p}}catch(a){return{timeStamp:new Date,i:-4,ka:-4,G:null,
L:!1,ga:p}}else return{timeStamp:new Date,i:-2,ka:-2,G:null,L:!1,ga:0};else return{timeStamp:new Date,i:-1,ka:-1,G:null,L:!1,ga:0}};this.pe=function(b,k){this.b.a("c11");var c=null,g=null;if(null!=b.G){var d=b.G.j;k<=this.O.ef&&(c=0<=b.i||-5==b.i?b.L&&b.i>=this.O.$a||0==b.L&&50<=b.i?!0:!1:null,g=b.L?this.O.$a/100:.5,g=0==c?0>d.s+d.m*g?!0:!1:1==c?!1:null)}return{ed:g,fd:c}};this.vb=function(b){this.b.a("c12");var k=null;if(2!=b.ga&&512!=b.ga&&null!=b.G){var c=b.G.Jb,g=b.G.j;(c&this.ja.Pb)==this.ja.Pb&&
(c&this.ja.Qb)==this.ja.Qb&&(k=this.ic(b.G.za,{left:g.H,top:g.I,right:g.H+g.o,bottom:g.I+g.m},b.G.fa,g.rect),k=0<=b.i?b.L&&k>=this.O.$a||0==b.L&&50<=k?!1:!0:null)}this.b.a("c12e");return k};this.pd=function(){function b(c){c.forEach(function(c){k.tb=c})}var k=this;"undefined"!=typeof IntersectionObserver&&null!=this.f&&(p=512,this.zb=new IntersectionObserver(b,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.zb.observe(this.f),this.ub=!0)};this.Ne=function(){this.f=null;null!=this.zb&&(this.zb.disconnect(),
this.tb=null,this.ub=!1)}}
function J(){this.getElementVolume_object=function(b){var e=b.getAttribute("width"),f=b.getAttribute("height");null==e||""==e||null==f||""==f?(b=b.parentNode,b={w:b.clientWidth,h:b.clientHeight}):b={w:e,h:f};return b};this.We=function(b){var e=0;try{for(;null!=b&&10>e;){if("none"==window.getComputedStyle(b).display||"hidden"==window.getComputedStyle(b).visibility)return!1;b=b.parentElement;e++}}catch(f){}return!0};this.la=function(b,e){this.a("cm1");var f=null,m=b.nodeName.toLowerCase();e&&this["getElementVolume_"+
m]&&(f=this["getElementVolume_"+m](b));if(!f&&(f=this.qb(b),this.a("cm2e"),!f||1>=f.w||1>=f.h))return this.a("cm1e"),{w:0,h:0};f.w.indexOf&&f.w.indexOf("px")&&(f.w=f.w.replace("px",""));f.h.indexOf&&f.h.indexOf("px")&&(f.h=f.h.replace("px",""));this.a("cm1e");return f};this.qb=function(b){this.a("cm2");try{var e;return document.body.getBoundingClientRect&&(e=b.getBoundingClientRect())?{w:e.right-e.left,h:e.bottom-e.top,l:e.left,t:e.top,Jc:e.bottom,r:e.right}:null}catch(f){return null}};this.Ba=function(b){this.a("ff8");
b=b.document.documentElement.clientHeight?b.document.documentElement:b.document.body;this.a("ff8e");return b};this.Xc=function(b,e){this.a("ff9");var f=0,m=!1;if(b.document.all)for(var h=0;h<b.document.all.length;h++)"BODY"==b.document.all[h].nodeName&&(m=!0),m&&("width"==e?b.document.all[h].width>f&&(f=b.document.all[h].width):b.document.all[h].height>f&&(f=b.document.all[h].height));this.a("ff9e");return f};this.ld=function(b,e){for(var f=this.Ba(b),m=b.innerWidth||f.clientWidth||this.Xc(b,"width"),
f=b.innerHeight||f.clientHeight||this.Xc(b,"height"),h=e.length,r=0,l=0;l<h;l++)if(15>=Math.abs(m-e[l].w)){r=e[l].h.length;for(m=0;m<r;m++)if(15>=Math.abs(f-e[l].h[m]))return!0;break}return!1};this.Gf=function(b){for(var e=[],f=-1;e[++f]=b[f];);e.length--;return e};this.Mb=function(b,e,f,m){var h=b.getElementsByTagName("*"),h=this.Gf(h);h.unshift(b);for(var r=["EMBED","IFRAME","OBJECT","IMG","DIV"],l=[],w=0;w<h.length;w++){var p=h[w];if(-1!=r.indexOf(p.nodeName)){var t=m(p);t&&l.push({Ic:t.w*t.h,
w:t.w,h:t.h,type:p.nodeName||"other",ke:p})}}l=l.sort(function(b,c){return c.Ic-b.Ic||r.indexOf(c.type)-r.indexOf(b.type)});(e=0<l.length&&l[0].w>e&&l[0].h>f?l[0].ke:null)&&b&&(e.nc=b.nc);return e};this.hd=function(b,e){this.a("ff10");try{if(!b)return!1;for(e||(e=window);b!=e.document&&b.parentNode;)b=b.parentNode;this.a("ff10e");return b==e.document}catch(f){return!1}};this.jc=function(b,e){var f=e.parent,m={left:0,right:0,top:0,bottom:0};if(b){var h=b.getBoundingClientRect();e!=f&&this.Rb(e,f)&&
(m=this.jc(e.frameElement,f));m={left:h.left+m.left,right:h.right+m.left,top:h.top+m.top,bottom:h.bottom+m.top}}return m};this.Rb=function(b,e){var f=!1;if(b==e)f=!0;else try{b.document.domain==e.document.domain&&(f=!0)}catch(m){}return f};this.xe=function(b){if(b)try{if(b.contentDocument&&this.gd(b.contentDocument))return b.contentDocument;if(b.contentWindow&&this.yb(b.contentWindow))return b.contentWindow.document}catch(e){}return null};this.Je=function(b){return b?b.defaultView||b.parentWindow:
null};this.Qe=function(b,e){return-1<e.indexOf(b)};this.re=function(b){try{return b!=b.top&&b.parent&&this.yb(b.parent)?b.parent:null}catch(e){return null}};this.yb=function(b){try{return b&&b.document&&this.gd(b.document)?!0:!1}catch(e){return!1}};this.gd=function(b){try{return b&&b.getElementsByTagName&&b.getElementById?!0:!1}catch(e){return!1}};this.Dc=function(b,e){var f=e.parent,m={w:0,h:0,left:0,right:0,top:0,bottom:0};b&&(m=this.jc(b,e),m.w=m.right-m.left,m.h=m.bottom-m.top,e!=f&&this.Rb(e,
f)&&(f=this.Dc(e.frameElement,f),f.bottom<m.bottom&&(f.bottom<m.top&&(m.top=f.bottom),m.bottom=f.bottom),f.top>m.top&&(f.top>m.bottom&&(m.bottom=f.top),m.top=f.top),f.right<m.right&&(f.right<m.left&&(m.left=f.right),m.right=f.right),f.left>m.left&&(f.left>m.right&&(m.right=f.left),m.left=f.left),m.w=m.right-m.left,m.h=m.bottom-m.top));return m};this.ac=function(b,e){return function(){return b.apply(e,arguments)}};this.ua=function(b){try{return b?b.length?b.length:0:0}catch(e){return 0}};this.lc=function(b){for(var e=
[],f=0;f<b.length;f++)this.We(b[f])&&e.push(b[f]);return e};this.a=function(b){try{maxLength=3,$dv&&($dv.Na=$dv.Na||[],$dv.Na.push(b),$dv.Na.length>maxLength&&$dv.Na.shift())}catch(e){}};this.sb=function(){try{return $dv&&$dv.Na?"&dvp_log="+$dv.Na.join():""}catch(b){return""}};this.xa=function(b){if(b.$sf&&b.$sf.ext)if(b.$sf.ext.geom){if(b=this.Ma(b),null!=b&&b.win&&(0<b.win.h||0<b.win.w))return this.xa=function(){return!0},!0}else if(b.$sf.ext.inViewPercentage)return!0;this.xa=function(){return!1};
return!1};this.Ma=function(b){b.$sf.ext.geom&&(this.Ma="function"==typeof b.$sf.ext.geom?function(b){return b.$sf.ext.geom()}:function(b){return b.$sf.ext.geom});return this.Ma(b)};this.qc=function(b){return b.context&&b.context.observeIntersection?!0:!1};this.wb=function(){var b=!1;if(1==this.Va("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(b=!0);return b};this.xb=function(b,e,f){var m=f&&f.Enums.BrowserId||window.$dv.Enums.BrowserId;if(b==(f&&f.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&
e.X===m.Safari&&(null===e.wa||void 0===e.wa||!/^[3-8]/.test(e.wa)))return this.xb=function(){return!0},!0;this.xb=function(){return!1};return!1};this.Va=function(b){var e,f=this.Uc();f&&f.AVO&&(e=f.AVO[b]);return e};this.Uc=function(){var b={},e=window.$dv,f=window.$uid;e.tags&&e.tags[f]&&(b=e.tags[f]);return b};this.Ib=function(){return 1==this.Va("sam")?!0:!1};this.Xa=function(b){return b.document.hasFocus()};this.La=new function(){var b=this;b.cache=[];window.addEventListener?b.add=function(e,
f,m,h,r){if("undefined"==typeof h||null==h)h=window;h.addEventListener(e,f,m);r&&b.cache.push([e,f,m,h])}:window.attachEvent?b.add=function(e,f,m,h,r){if("undefined"==typeof h||null==h)h=window;h["e"+e+f]=f;h[e+f]=function(){h["e"+e+f](window.event)};h.attachEvent("on"+e,h[e+f]);r&&b.cache.push([e,f,m,h])}:b.add=function(){};window.removeEventListener?b.remove=function(b,f,m,h){if("undefined"==typeof h||null==h)h=window;h.removeEventListener(b,f,m)}:window.detachEvent?b.remove=function(b,f,m,h){if("undefined"==
typeof h||null==h)h=window;h.detachEvent("on"+b,h[b+f]);h[b+f]=null;h["e"+b+f]=null}:b.remove=function(){};b.flush=function(){for(var e=0;e<b.cache.length;e++)b.remove.apply(b,b.cache[e]);b.cache=[]}};this.Wc=function(b,e){var f=b||"",m="";if(e&&(f+=": "+(e.message||""),e.stack)){var m=e.stack||"",h=m.indexOf("at ");0>h&&(h=0);m=", Stack: "+m.slice(h,m.length)}f=f.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");m=m.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,
"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");h=null;try{h=encodeURIComponent(f+m).slice(0,500)}catch(r){try{h=encodeURIComponent(f).slice(0,500)}catch(l){h=f.slice(0,500)}}return h}}
function ma(b,e,f,m,h){function r(c,b){for(var d=[],a=0;a<p.length;a++){var n=[],n=b(c,p[a]),k=l.ua(n);if(0!=k){var f=l.Je(p[a]);if(null!=f)for(var e=0;e<k;e++)try{n[e].nc=f,d.push(n[e])}catch(h){}}}return d}var l=new J,w="Microsoft Internet Explorer"==navigator.appName;this.c=m;this.window=f;this.Kb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.Ab=[1==w?"object":"embed",1==w?"embed":"object","href","img",
"span","iframe","frameElement","div"];this.Fb=this.f=null;this.dataObj=b;this.dvObj=b.dvObj||window.$dv;this.J={X:this.dvObj.CommonData.BrowserId,wa:this.dvObj.CommonData.BrowserVersion};this.Y=this.dvObj.Enums.BrowserId;this.S=h;this.aa=this.dvObj.Enums.TrafficScenario;this.fe=function(){var c=this.dataObj.cc+"-"+this.dataObj.$b;this.dataObj.isBrandShieldOrigin&&(c+="-bs");return c.replace(RegExp(",","g"),";")};this.yc=this.fe();this.V=e;this.M={N:{h:1,w:1},Nf:{h:10,w:10},cf:10};115==this.dataObj.Wb&&
(this.M.N.h=20,this.M.N.w=20);this.dataObj.findclass&&1==this.dataObj.findclass&&this.Ab.push("classDeclaration");this.dataObj.kb&&0<this.dataObj.kb.length&&this.Ab.unshift("searchCustomElementsFromTag");this.searchByAdSrvId_8=function(c,b){l.a("a1");var d=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(c);return null!=d&&(d=d.toString(),d.replace(RegExp("-","g"),"")==b)?!0:!1};this.dc=this["searchByAdSrvId_"+(this.dataObj?this.dataObj.Wb||"":"")];this.getElementsByClassName=function(c,b){return r(c,function(c,
a){l.a("ff1");var n=a.getElementsByClassName(c);l.a("ff1e");return"1"!=b?n:l.lc(n)})};this.querySelectorAll=function(c,b){return r(c,function(c,a){l.a("ff3");var n=a.querySelectorAll("."+c);l.a("ff3e");return"1"!=b?n:l.lc(n)})};this.getElementsByTagName=function(c,b){return r(c,function(c,a){l.a("ff4");var n=a.getElementsByTagName(c);l.a("ff4e");return"1"!=b?n:l.lc(n)})};this.classDeclaration=function(){l.a("a9");var c="undefined"!==typeof window.document.getElementsByClassName,b="undefined"!==typeof window.document.querySelectorAll;
if(!(1>this.dataObj.K.length)){var d=[];if(c)d=this.getElementsByClassName(this.dataObj.K,this.dataObj.displaynon);else if(b)d=this.querySelectorAll(this.dataObj.K,this.dataObj.displaynon);else return;c=l.ua(d);for(b=0;b<c;b++)if(d[b]&&!this.qa(d[b])){var a=l.la(d[b]);if(a&&a.h>this.M.N.h&&a.w>this.M.N.w&&this.ba(d[b])){this.f=d[b];break}}}};this.searchCustomElementsFromTag=function(){for(var c=0;c<this.dataObj.kb.length&&(this.Qc(this.dataObj.kb[c]),!this.f);c++);};this.Qc=function(c){if(!(1>this.dataObj.K.length)){c=
this.getElementsByTagName(c,this.dataObj.displaynon);for(var b=l.ua(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d],!0)&&!this.qa(c[d])){var a=l.la(c[d]);if(a&&a.h>this.M.N.h&&a.w>this.M.N.w&&this.ba(c[d])){this.f=c[d];break}if((a=l.Mb(c[d],this.M.N.w,this.M.N.h,l.ac(l.la,l)))&&this.ba(a)){this.f=a;this.ba(c[d]);break}}}};this.div=function(){this.Qc("div")};this.span=function(){l.a("a10");if(!(1>this.dataObj.K.length))for(var c=this.getElementsByTagName("span",this.dataObj.displaynon),b=l.ua(c),
d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d],!0)&&!this.qa(c[d])){if(this.Pe(c[d])){this.f=c[d];break}var a=l.Mb(c[d],this.M.N.w,this.M.N.h,l.ac(l.la,l));if(a&&this.ba(a)){this.f=a;this.ba(c[d]);break}}};this.object=function(){l.a("a11");for(var c=this.getElementsByTagName("object",this.dataObj.displaynon),b=l.ua(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d])&&!this.qa(c[d])){var a=l.Mb(c[d],this.M.N.w,this.M.N.h,l.ac(l.la,l));if(a&&this.ba(a)){this.ba(c[d]);this.f=a;break}}};this.embed=function(){l.a("a12");
for(var c=this.getElementsByTagName("embed",this.dataObj.displaynon),b=l.ua(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d])&&!this.qa(c[d])){var a=l.la(c[d]);if(a&&a.h>this.M.N.h&&a.w>this.M.N.w&&this.ba(c[d])){this.f=c[d];break}}};this.href=function(){l.a("a13");for(var c=this.getElementsByTagName("a",this.dataObj.displaynon),b=l.ua(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d])&&!this.qa(c[d])){var a=c[d].getElementsByTagName("img");if(0<a.length){var n=l.la(a[0]);if(n&&n.h>this.M.N.h&&n.w>
this.M.N.w&&this.ba(c[d])){this.f=a[0];break}}}};this.img=function(){l.a("a14");for(var c=this.getElementsByTagName("img",this.dataObj.displaynon),b=l.ua(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d])&&0>c[d].src.indexOf("event")&&!this.qa(c[d])){var a=l.la(c[d]);if(a&&a.h>this.M.N.h&&a.w>this.M.N.w&&this.ba(c[d])){this.f=c[d];break}}};this.iframe=function(){l.a("a15");for(var c=this.getElementsByTagName("iframe",this.dataObj.displaynon),b=l.ua(c),d=0;d<b&&!this.Gc(c[d]);d++);};this.frameElement=
function(){try{l.a("a16"),this.S==this.aa.SameDomain&&this.Gc(this.window.frameElement)}catch(c){}};this.Gc=function(c){l.a("a17");return this.Aa(this.dataObj,c)?this.Vd(c):!1};this.ba=function(c){l.a("a18");if(c&&0==this.qa(c))try{var b=c.getAttribute("dvvisit");b?c.setAttribute("dvvisit",b+","+this.yc):(l.a("ff5"),b=this.window.document.createAttribute("dvvisit"),l.a("ff5e"),b.value=this.yc,c.setAttributeNode(b));return!0}catch(d){}return!1};this.hf=function(c){c&&c.hasAttribute&&c.hasAttribute("dvvisit")&&
c.removeAttribute("dvvisit")};this.nf=function(){this.hf(this.f);this.f=null};this.qa=function(c){l.a("a19");if(c&&(c=c.getAttribute("dvvisit"))){c=c.split(",");for(var b=0;b<c.length;b++)if(c[b]==this.yc)return!0}return!1};this.Pe=function(c){l.a("a20");return c&&"1"==c.getAttribute("adunit")?!0:!1};this.Vd=function(c){l.a("a21");if(c&&!this.qa(c)){var b=l.la(c);if(b&&b.h>this.M.N.h&&b.w>this.M.N.w&&this.ba(c))return this.f=c,!0}return!1};this.Aa=function(c,b,d){l.a("a22");var a=null;return c.K&&
0<c.K.length&&(this.Ec=1==c.Xe?this.Jd:this.Nb,a=this.Pd(c,b,d))||!this.f&&(a=this.Qd(c,b))?!0:!1};this.Pd=function(c,b,d){l.a("a23");var a;try{if(c.Nc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(a=this.ma(b.id,c.K))||(a=this.ma(b.src,c.K));a||(a=this.ma(b.href,c.K));a||(a=this.ma(b.getAttribute("flashvars"),c.K));a||(a=this.ma(b.name,c.K));!a&&this.dataObj.findclass&&1==this.dataObj.findclass&&(a=this.ma(b.getAttribute("class"),c.K));if(!a&&this.dataObj.Ja&&0<this.dataObj.Ja.length)for(var n=
this.dataObj.Ja,k=0;k<n.length&&!(a=this.ma(b.getAttribute(n[k]),c.K));k++);a||d||(a=this.ma(b.innerHTML,c.K));a&&!d&&(a=this.Od(c,b));return a}catch(f){return a}};this.Qd=function(c,b){l.a("a24");var d;try{if(c.Nc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(d=this.Fa(b.id,c))||(d=this.Fa(b.src,c));d||(d=this.Fa(b.href,c));d||(d=this.Fa(b.Sf,c));d||(d=this.Fa(b.name,c));d||(d=this.Fa(b.innerHTML,c));if(!d&&this.dataObj.Ja&&0<this.dataObj.Ja.length)for(var a=this.dataObj.Ja,n=0;n<a.length&&
!(d=this.ma(b.getAttribute(a[n]),c.K));n++);return d}catch(k){return d}};this.Fa=function(c,b){l.a("a25");if(!c)return!1;c=c.toLowerCase();for(var d=0;d<this.Kb.length;d++){var a;if(b.Hc&&(a=(this.Kb[d][0]+b.Hc).toLowerCase(),a=c.indexOf(a),-1<a)||b.nd&&(a=(this.Kb[d][0]+b.nd).toLowerCase(),a=c.indexOf(a),-1<a))return!0}return!1};this.Od=function(c,b){l.a("a26");return null==c.jb||""==c.jb?!1:this.ma(this.Id(b),c.jb)};this.Id=function(c){l.a("a27");if(c.outerHTML)return c.outerHTML;for(var b=c.attributes.length,
d="",a=0;a<b;a++)d=d+c.attributes[a].nodeName+"="+c.attributes[a].nodeValue+" ";return d+c.innerHTML};this.ma=function(c,b){l.a("a28");return!c||!b||5>b.length?!1:null!=(this.Ec?this.Ec(c,b):this.Nb(c,b))?!0:this.dc&&"function"===typeof this.dc?this.dc(c,b):!1};this.Jd=function(c,b){l.a("a29");var d;try{d=(new RegExp(b)).exec(c)}catch(a){d=this.Nb(c,b)}return d};this.Nb=function(c,b){l.a("a30");var d=null;-1!==c.indexOf(b)&&(d=c);return d};this.me=function(c){l.a("a31");if(this.ze())return this.c.Dd(),
this.pc||(this.pc=!0),this.f;if(this.dataObj.K&&0<this.dataObj.K.length&&!0===this.pc&&1<c)return this.f;"1"!=this.dataObj.displaynon&&(c=this.Ae())&&c.node&&(this.c.Cd(c.Ka),this.f=c.node);return this.f};var p=[];this.ze=function(){l.a("32");if(this.dataObj.K&&0<this.dataObj.K.length){var c=this.Ab.length,b=this.window,d=0,a=[];try{do{a.push(b.document);for(var n=a,k=b.document.getElementsByTagName("iframe")||[],f=0;f<k.length||25>f;f++){var e=null,e=l.xe(k[f]);void 0!==e&&null!==e&&0==l.Qe(e,n)&&
n.push(e)}b=l.re(b)}while(b&&10>++d)}catch(h){}p=a;for(b=0;b<c;b++)if(this[this.Ab[b]](),this.f){this.Fb=this.f;break}}return this.f};var t=[],k=["object","embed","img","iframe"];this.dataObj.spotXmode&&(k=["object","embed","video","iframe"]);this.Te=function(c){l.a("a33");c=l.la(c);return this.Ue(c)};this.Ue=function(c){if(c){var b=c.w;c=c.h;for(var d=e.length,a=0,n=0;n<d;n++)if(15>=Math.abs(b-e[n].w))for(var a=e[n].h.length,k=0;k<a;k++)if(15>=Math.abs(c-e[n].h[k]))return!0}return!1};this.ue=function(){l.a("a34");
return this.ve()||this.rf()};this.rf=function(){l.a("a35");var c=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),b=[],d=window.parent;l.a("ff6");try{b=d.document.getElementsByTagName("script")}catch(n){}l.a("ff6e");for(var d=b.length,a=0;a<d;a++)if(b[a]&&b[a].id&&b[a].id.substr(7)==c)return b[a];return null};this.ve=function(){l.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:
null};this.Ae=function(){l.a("a37");var c=this.ue(),b=null;c&&(b=this.$d(c));return b};this.$d=function(c){l.a("a38");var b={node:c,Ka:0};c=[];for(t=[];b||0<c.length;){try{var d;a:{var a=b.node;try{if(a&&-1!=k.indexOf(a.nodeName.toLowerCase())){d=!0;break a}}catch(f){}d=!1}if(d&&this.Te(b.node)&&!this.qa(b.node)&&this.ba(b.node))return b;if(b.Ka<=this.M.cf){var n,e=b.node,h=b.Ka,b=[],m=e.parentNode;m&&-1==t.indexOf(m)&&(t.push(m),b.push({node:m,Ka:h+1}));if(e.hasChildNodes())for(var p=0;p<e.childNodes.length;p++)e.childNodes[p]&&
-1==t.indexOf(e.childNodes[p])&&1===e.childNodes[p].nodeType&&(t.push(e.childNodes[p]),b.push({node:e.childNodes[p],Ka:h+1}));var r,w=e,U=[],A=null;w&&w.parentNode&&(A=w.parentNode.firstChild);for(;A;)1===A.nodeType&&A!==w&&U.push(A),A=A.nextElementSibling||A.nextSibling;r=U;for(p=0;p<r.length;p++)r[p]&&-1==t.indexOf(r[p])&&1===r[p].nodeType&&(t.push(r[p]),b.push({node:r[p],Ka:h+1}));if(n=b)for(b=0;b<n.length;b++)c.push(n[b])}}catch(f){}b=c.shift()}return{node:null}};return this}
function dv_CustomClientViewAssureService(b){function e(b){return{settings:b.settings,buckets:0,reported:!1,eventId:b.eventId,Qa:b.Qa,mb:b.mb}}this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this.b=new J;var f=[],m=null,h=null,r=null,l=null;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&(m=this.dvObj.tags[this.impressionId].cvmSettings,h=this.dvObj.tags[this.impressionId].billable,r=this.dvObj.tags[this.impressionId].bprjct,l=this.dvObj.tags[this.impressionId].gmmod);
this.Bc=window.dv_cvmSettings||m||b.cvmSettings;this.Xb=window.dv_billable||h||b.billable;this.Mc=window.Uf||r||b.bprjct;this.ad=window.Vf||l;this.ge=new e({settings:this.Bc,eventId:6,Qa:["CustomViewabilityViewable"]});var w=this.b.Va("rpv"),m=this.b.Uc().bgm;b.Za=1==w&&1==m;this.Lc=new e({settings:this.Xb,eventId:17,Qa:b.Za?["BillableViewedImpression"]:["BillableViewedImpression","GroupMPassedImpression"],mb:!0});this.Bc&&f.push(this.ge);this.Xb&&f.push(this.Lc);b.na=b.na||[];m={serverProperties:{projected:"bp",
viewed:"bpv",viewedRate:"bpvr",error:"bperr"},reportQueryString:{projected:"isbprjct",measurems:"isbmms",viewedms:"isbvms",viewrate:"prjctbvr",error:"prjctber"}};this.Mc&&(m={serverData:this.Mc,projectionData:m,reportRTN:!0},b.na.push(m));m={serverProperties:{projected:"gmp",viewed:"gmpv",viewedRate:"gmpvr",error:"gmperr"},reportQueryString:{projected:"isgmmod",measurems:"isgmmims",viewedms:"isgmpims",viewrate:"modgmvr",error:"modgmer"}};this.ad&&(m={serverData:this.ad,projectionData:m,reportRTN:!0},
b.na.push(m));this.Zd=dv_InViewService;this.Zd(b);var p=this.Ob;this.Ob=function(b){b=p(b);for(var c=0;c<f.length;c++){var e=this.He(b,f[c]);this.Hf(e,f[c]);this.Xd(f[c])}return b};var t=this.Ra;this.Ra=function(b,c){t(b,c);this.Xb&&1==this.ec&&(this.ya(["BillableMeasuredImpression"]),w?0==this.dataObj.Za&&this.ya(["GroupMMeasuredImpression"]):1!=this.dataObj.irtf&&this.ya(["GroupMMeasuredImpression"]))};this.He=function(b,c){"undefined"===typeof c.settings.focus||c.settings.focus||(b.i=b.ka);return b};
this.Hf=function(b,c){(!c.settings.measureType||"consecutive"==String(c.settings.measureType).toLowerCase())&&b.i<c.settings.adArea?c.buckets=0:b.i>=c.settings.adArea&&(!c.mb||1!=this.dataObj.irtf)&&(c.buckets+=this.ca.interval);c.L=b.L};this.Xd=function(b){b.mf||b.mb&&1==this.dataObj.irtf||!(this.Rd(b)||b===this.Lc&&b.settings&&!b.settings.doNotReportViewedOnLargeAd&&b.L)||(this.R.T(this.c.da(b.eventId),b.eventId),b.Qa&&this.ya(b.Qa),b.mf=!0)};this.Rd=function(b){return b.buckets>=b.settings.duration?
!0:!1}}
function dv_InViewService(b){function e(){null===h.interval&&(h.interval=setInterval(h.ye(),h.ca.interval))}function f(){if(!1===h.kd){h.kd=!0;try{h.b.La.remove("load",arguments.callee,!1,element)}catch(a){}h.Db();h.b.a("s41");h.va=new la(h.be?h.be:h.window,h.f,h.S,h.J,h.O,h.c.Zb,h.dvObj,h.impressionId);h.b.a("s42");h.Ld();h.start()}}function m(a,b){h.b.La.add("click",function(){h.Sb(!0);$dv.registerEventCall(h.impressionId,"ad"==b?{dvp_csad:1}:{dvp_csifr:1});h.b.La.remove("click",arguments.callee,!1,
a)},!1,a,!1)}var h=this;this.md=10;this.Vb=b.serverSettings&&b.serverSettings.jsVersion?b.serverSettings.jsVersion:"628";this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this._minor_version="0";this.b=new J;this.Ie=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,d=0;d<b;d++)if(c=a[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.kd=!1;var r={serverProperties:{projected:"p",error:"perr",viewed:"pv",featurebit:"fb",viewedRate:"pvr"},
reportQueryString:{projected:"isprjct",measurems:"ismms",viewedms:"isiabvms",viewrate:"prjctvr",error:"prjcter"}},l=!1,w=!1;this.na=b.na||[];(this.If=b.prjct)&&this.na.push({serverData:b.prjct,projectionData:r,kf:!0,Jf:["MeasurementCapabilityDetected","ProjectedMeasured","IabView","ProjectedAssignedViewed"],df:["MeasurementCapabilityDetected","ProjectedMeasured"]});r={serverProperties:{projected:"up",error:"uperr",viewed:"upv",viewedRate:"upvr"},reportQueryString:{projected:"isuprjct",measurems:"isumms",
viewedms:"isuiabvms",viewrate:"uprjctvr",error:"uprjcter"}};this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].uprjct&&this.na.push({serverData:this.dvObj.tags[this.impressionId].uprjct,projectionData:r});this.De=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.$c=function(){return((new Date).getTime()+
""+Math.floor(1E6*Math.random())).substr(0,16)};this.Z=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.Fe=function(){var a=this.Z("uid",this.U);null==a?(a=this.$c(),this.U=this.U+"&uid="+a):""==a&&(a=this.$c(),this.U=this.U.replace("&uid=","&uid="+a));return a};this.vc=function(a,b,c,d){if(d&&d.insertBefore&&d.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in c)a.style[e]=
c[e];d.insertBefore(a,d.firstChild);return a}return null};this.ae=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.S=this.dvObj.CommonData.Scenario||this.ae();this.J={X:this.dvObj.CommonData.BrowserId,wa:this.dvObj.CommonData.BrowserVersion};this.Y=this.dvObj.Enums.BrowserId;this.aa=this.dvObj.Enums.TrafficScenario;this.bb="default";this.dataObj=
b;this.window=b.tagWindow||parent.window||window;this.Fb=this.f=null;this.Ac=this.Ta=!1;this.sc=!0;this.interval=null;this.U=this.Ie();this.Oa=this.De();this.gf=b.serverSettings&&b.serverSettings.protocol&&0==b.serverSettings.protocol.indexOf("http")?b.serverSettings.protocol:window.location.protocol?window.location.protocol+"//":"http://";this.ca=window.je||this.window.je||{interval:100,Ca:{"default":{time:null,La:["beforeunload","unload"],yd:9E5}}};this.od={};var r="tps300.doubleverify.com",p=null;
try{this.dvObj.tags[this.impressionId].ServerPublicDns&&(r=this.dvObj.tags[this.impressionId].ServerPublicDns)}catch(a){}this.ia=window.dv_configServer||this.window.dv_configServer||{protocol:this.gf,port:"",domain:r,api:"event.jpg"};this.W=window.ie||this.window.ie||{interval:1E3,ea:6};r=b&&b.Ad?b.Ad:!1;b=b&&b.Bd?b.Bd:!1;!1!==r&&!1!==b&&(this.W.interval=r,this.W.ea=b,$dv.registerEventCall(this.impressionId,{Qf:this.W.interval,Rf:this.W.ea}));b=$dv&&$dv.CommonData&&(2==$dv.CommonData.deviceType||
3==$dv.CommonData.deviceType);this.ee={lb:12,gc:10,$a:30};this.O={Firefox:{$:115},Chrome:{$:89},Safari:{$:38},Explorer:{$:55},ef:500,Ff:0==b,$a:30};var t=!1,k=0,c=[5,10,15];window.devicePixelRatio&&(this.O.Firefox.$=0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);
this.V=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},
{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180]},{w:980,h:[90,120]}];this.dataObj.spotXmode&&(this.V.push({w:320,h:[240]}),this.V.push({w:400,h:[300]}),this.V.push({w:450,h:[338]}),this.V.push({w:600,h:[800]}),this.V.push({w:640,h:[360]}),this.V.push({w:854,h:[480]}),this.V.push({w:500,h:[375]}));b&&(this.V.push({w:320,h:[50,100,480]}),this.V.push({w:300,
h:[50,31]}),this.V.push({w:120,h:[20]}),this.V.push({w:168,h:[28]}),this.V.push({w:216,h:[36]}),this.V.push({w:292,h:[30]}));this.bd=this.Fe();this.fc=!1;this.Lb=function(a,b){this.window.Rc||(this.window.Rc=[]);this.window.Rc.push({caller:a,Tf:b})};this.startTime=(new Date).getTime();this.Wd=4;this.Fc=0;this.mc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,projection:9,fraudMeasured:10,errorlevel1:16,Of:17,interval:32};this.ec=
!1;this.zd=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.c.se();this.window.dv_logObject[this.bd]=a}this.b.a("ie16e")};this.Gb=function(a){this.b.a("ie17");this.Gb=this.fc?function(a){this.c.td(a);this.zd()}:function(a){this.c.td(a)};this.Gb(a)};this.zc=function(a,b){this.zc=this.fc?function(a,b){this.c.sd(a,b);this.zd()}:function(a,b){this.c.sd(a,b)};this.zc(a,b)};this.Db=function(){this.b.a("s4");this.f=this.hb.me(this.W.ea);this.Fb=this.hb.Fb;!this.f&&this.S==this.aa.CrossDomain&&
this.b.xa(this.window)&&(this.W.ea=0);this.f?(this.sf(),this.c.jf(this.f),l||(m(this.f,"ad"),l=!0),w||this.S!=this.aa.CrossDomain&&this.S!=this.aa.SameDomain||(m(window.parent,"ifr"),w=!0),setTimeout(e,this.hb.pc?10:50)):0<this.W.ea?(this.W.ea--,this.tf(),setTimeout(this.ne(),this.W.interval)):(this.S==this.aa.CrossDomain&&(this.b.ld(this.window,this.V)||this.b.xa(this.window))?(this.f=this.b.Ba(this.window),this.c.rd()):this.S==this.aa.SameDomain&&this.b.ld(this.window,this.V)?(this.f=this.b.Ba(window.parent),
this.c.rd(),this.de()):this.W.ea=-1,setTimeout(e,10));this.b.a("s4e")};this.de=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),c=b.length,d=0;d<c;d++)b[d].contentWindow==a&&(this.f=b[d],this.window=a.parent);this.b.a("ff26e")};this.tf=function(){this.dataObj.K&&this.dataObj.jb?this.c.xf():this.c.yf()};this.sf=function(){this.b.a("s9");this.Ta=!0;this.c.uf();this.b.a("s9e")};this.Yd=function(){this.dataObj.Wb=
this.Z("adsrv",this.U)||"";this.dataObj.K=this.Z("btreg",this.U)||"";this.dataObj.nd=this.Z("plcid",this.U)||"";"8"==this.dataObj.Wb&&""==this.dataObj.btreg&&(this.dataObj.K=this.dataObj.plcid);this.dataObj.jb=this.Z("btadsrv",this.U)||"";this.dataObj.Hc=this.Z("adid",this.U)||"";this.dataObj.Xe=this.Z("isbtregex",this.Oa)||"";this.dataObj.cc=this.Z("ctx",this.U)||"";this.dataObj.$b=this.Z("cmp",this.U)||"";this.dataObj.Ze=this.Z("lomd",this.U)||"";this.dataObj.findclass=this.Z("findclass",this.Oa)||
"";this.dataObj.displaynon=this.Z("displaynon",this.Oa)||"";this.dataObj.Nc=this.Z("bsdvview",this.Oa)||"";var a=this.Z("bttag",this.Oa)||"";this.dataObj.kb=0<a.length?a.split("|"):[];a=this.Z("btattb",this.Oa)||"";this.dataObj.Ja=0<a.length?a.split("|"):[]};this.ab=function(a){a=this.ya(a);return 0<a.length?"&tagServiceResult="+encodeURIComponent(a.join(",")):""};this.ya=function(a){if(!this.dvObj||!this.impressionId)return[];for(var b=[],c=0;c<a.length;c++){var d=this.dvObj.pubSub.publish(a[c],
this.impressionId)||null;null!=d&&b.push(d)}return b};this.Me=function(a){1==a&&(this.c.Ef(),this.dvObj&&this.impressionId&&this.c.rc()&&(a=this.ab(["MeasurementCapabilityDetected","GeoMeasured"]),this.R.T(this.c.da(this.logEvents.fraudMeasured)+a,this.logEvents.fraudMeasured)))};this.Le=function(a){var b="",c=a.serverData,d=a.projectionData;1==c[d.serverProperties.featurebit]&&(b=1==c[d.serverProperties.viewed]?this.ab(a.Jf):this.ab(a.df));return b};this.Ed=function(){this.dataObj.serverSettings&&
this.dataObj.serverSettings.TKH&&(this.U+="&TKH="+this.dataObj.serverSettings.TKH)};this.he=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||
this.he();var a=this.ia.protocol+this.ia.domain+this.ia.port+"/"+this.ia.api;this.Ed();this.c=new aa(this.Vb,this.U,a,this.ee,this.dataObj);var b=new ba(this.window,this.bd);this.dataObj.isReportingDisabled?(X.prototype=b,this.R=new X):this.R=b;this.dataObj.isRTNsDisabled&&(this.ya=function(){return[]});this.fc=this.window.dv_logObject?!0:!1;this.zf();if(!this.c.Zb()&&(this.Ke(),void 0!=this.dataObj.prjct&&1==this.dataObj.prjct.p&&1==this.dataObj.prjct.fb))return;this.Me(this.dataObj.irtf);this.Yd();
this.hb=new ma(this.dataObj,this.V,this.window,this.c,this.S);var c=window.parent;"589953"==this.dataObj.cc&&"587351"==this.dataObj.$b||"589953"==this.dataObj.cc&&"616389"==this.dataObj.$b||"polite"==this.dataObj.Ze?(setTimeout(f,15E3),this.b.La.add("load",function(){setTimeout(f,1E3)},!1,c,!1)):f()}catch(d){var e=this;this.Sa(function(){e.Lb("inViewManager",d);e.c.wc("inViewManager",d);e.R.T(e.c.da(e.logEvents.errorlevel1),e.logEvents.errorlevel1)},"inViewManager",d)}};this.Ke=function(){for(var a=
"",b=0;b<this.na.length;b++){var c=this.na[b];this.c.Cf(c.serverData,c.projectionData);!0===c.kf&&(a+=this.Le(c))}0<this.na.length&&this.R.T(this.c.da(this.logEvents.projection)+a,this.logEvents.projection)};this.eb=function(a){this.b.a("ie20");-6!=a.i&&(-3==a.i||-5!=a.i&&0>a.i&&-1==this.W.ea)&&(this.Cc(),this.eb=function(){})};this.Cc=function(){this.R.T(this.c.da(this.logEvents.nonMeasurable),this.logEvents.nonMeasurable);this.ya(["ImpressionNotMeasured"]);this.Cc=function(){}};this.Ra=function(a,
b){a.b.a("ie21");if(0<=b.i||-5==b.i&&-1>=a.W.ea){if(a.dvObj&&a.impressionId&&0==a.c.rc()){a.b.a("ie23");var c=a.ab(["MeasurementCapabilityDetected","GeoMeasured"]);a.b.a("ie24");var d=a.c.da(a.logEvents.startMeasure);a.R.T(d+c,a.logEvents.startMeasure)}else a.R.T(a.c.da(a.logEvents.startMeasure),a.logEvents.startMeasure);a.ec=!0;a.Ra=function(){};a.eb=function(){}}a.b.a("ie22")};this.Sb=function(a){this.b.a("ie25");if(this.c.Vc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId&&0==this.c.rc()?
(this.b.a("ie28"),a=this.ab(["IabView","GeoViewed"]),this.b.a("ie29"),this.R.T(this.c.da(this.logEvents.iabViewable)+a,this.logEvents.iabViewable)):this.R.T(this.c.da(this.logEvents.iabViewable),this.logEvents.iabViewable),t=!0,this.Sb=function(){};this.b.a("ie26")};this.acumulateViewableTime=function(a){if(t&&this.c.Vc())for(k+=a,a=0;a<c.length;a++)null!=c[a]&&k>=1E3*c[a]&&(this.ya(["viewd"+c[a]+"sec"]),c[a]=null)};var g="hidden",d=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden",
"msHidden","oHidden"];for(hiddenProp in vis)if(vis[hiddenProp]in document){g=vis[hiddenProp];break}var a=1==this.b.Va("fcs"),b=!1;try{this.b.Xa(this.window),b=!0}catch(c){}var e=!1;try{this.b.Xa(this.window.top),e=!0}catch(c){}var f=null,f=a&&b&&this.J.X==this.Y.IE?function(){var a=h.b.Xa(h.window);h.S==h.aa.OnPage&&(a=a&&h.sc);return a}:a&&e?function(){var a=!0,a=h.b.Xa(h.window.top);h.S==h.aa.OnPage&&(a=a&&h.sc);return a}:"undefined"!==typeof document[g]?function(){return!h.window.document[g]}:
e?function(){return h.b.Xa(h.window.top)}:function(){return!0};this.hasFocus=function(){try{return f()}catch(a){d++,5<=d&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.kc=function(a){var b=a.va.we();a.b.a("ie12");null==this.f||-3==b.i||a.hasFocus()||(b.i=0);a.b.a("ie13");return p=b};this.Ob=function(a){a.b.a("ie1");var b=a.f?a.f.nc||a.window:a.window;a.va.f=a.f;a.va.window=b;a.b.a("ie2");b=a.kc(a);a.Ta&&(-1==b.i||-2==b.i)&&-1<=a.W.ea&&(a.qd(a),a.Db());a.b.a("ie3");-5==
b.i&&(a.W.ea--,a.c.ud(),a.Pa||(a.Pa=function(b){b=a.va.vb(b);a.c.cb(b)}));a.b.a("ie4");a.Pa&&0<b.i&&(a.Pa(b),a.Pa=null);a.b.a("ie5");if(a.Ta&&!a.Ac){a.Ac=!0;var c=a.va.vb(b);a.c.cb(c)}-5==b.i&&-1<=a.W.ea&&(a.qd(a),a.Db(),b=a.kc(a),-5==b.i&&0<a.W.ea&&a.c.pf());a.b.a("ie6");a.zc(b,a.ca.interval);a.b.a("ie7");a.Gb(b);a.b.a("ie8");a.c.wd(b.ga);a.eb(b);a.b.a("ie9");a.Ra(a,b);a.b.a("ie10");a.Sb();a.b.a("ie11");a.acumulateViewableTime(a.ca.interval);a.b.a("ie12");return b};this.qd=function(a){a.Ta=!1;a.f=
null;a.hb.nf();a.va.Ne()};this.ye=function(){this.b.a("s26");var a=this;return function(){try{a.Ob(a)}catch(b){a.Sa(function(){a.Fc<a.Wd&&(a.Fc++,a.Lb("getIntervalCallback",b),a.c.wc("getIntervalCallback",b),a.R.T(a.c.da(a.logEvents.errorlevel1),a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Zc=function(a){var b=this;return function(){b.Sa(function(){b.J.X==b.Y.IE?b.R.T(b.c.da(b.logEvents[a]),b.logEvents[a]):b.R.Hb(b.c.da(b.logEvents[a]),b.logEvents[a])},"getReportEventCallback")}};this.ne=
function(){var a=this;return function(){a.Sa(function(){a.Db();a.f||a.c.Eb()},"getAdLocateCallback")}};this.Wa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.sc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){try{b="",a.b?b=a.b.sb():a.b&&(b=a.b.sb()),a.R.T(a.ia.protocol+a.ia.domain+a.ia.port+"/"+a.ia.api+"?"+a.U+"&ctime="+(new Date).getTime()+"&evid="+a.logEvents.errorlevel1+"&jsver="+a.Vb+b+"&napr=getFocBluEventCallback: "+c.message,a.logEvents.errorlevel1)}catch(d){}}}};
this.Kd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.c.te().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.ec,totalPageTime:(a.c.pb()-a.c.Ce())/1E3,notApplicableTime:a.c.Yc()/
1E3}}catch(e){return{}}}}}catch(b){}};this.Ld=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=p.i;0<=p.i&&p.G&&p.G.j&&(a.adWidth=p.G.j.o,a.adHeight=p.G.j.m);return a};a.VA.getAdElem=function(){return h.f}}}catch(b){}};this.Kd();this.start=function(){this.b.a("s35");this.ff(this);var a;this.ca&&this.ca.Ca&&this.ca.Ca[this.bb]&&(a=this.ca.Ca[this.bb].La);
if(a)for(var b=a.length,c=0;c<b;c++)this.od[a[c]]=this.Zc(a[c]),this.Ia(this.window,a[c],this.od[a[c]]);this.Bf();this.ca&&this.ca.Ca&&this.ca.Ca[this.bb]&&this.ca.Ca[this.bb].yd&&setTimeout(this.lf(),this.ca.Ca[this.bb].yd)};this.lf=function(){var a=this;return function(){a.Zc("timeout")();clearInterval(a.interval);a.R.Hb=function(){};a.R.T=function(){}}};this.ff=function(a){try{var b=a.kc(a);-5==b.i&&(this.c.ud(),this.Pa||(this.Pa=function(b){b=a.va.vb(b);a.c.cb(b)}));if(a.Ta)if(this.Ac=!0,-5!=
b.i){var c=a.va.vb(b);a.c.cb(c)}else a.c.cb("true");a.c.wd(b.ga);var d=a.va.pe(b,a.c.Yc());a.c.wf(d);a.c.vd(b.i);a.Gb(b);a.eb(b);a.Ra(a,b)}catch(e){a.Sa(function(){a.Lb("onStartReport",e);a.c.wc("onStartReport",e);a.R.T(a.c.da(a.logEvents.errorlevel1),a.logEvents.errorlevel1)},"onStartReport",e)}};this.Bf=function(){this.Ia(this.window,"blur",this.Wa());this.Ia(this.window,"focus",this.Wa());this.Ia(this.window.document,"click",this.Wa());this.Ia(this.window.document,"mousedown",this.Wa());this.Ia(this.window.document,
"mouseup",this.Wa())};this.Ia=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.zf=function(){this.b.a("ff24");this.S==this.aa.CrossDomain?this.b.xa(this.window)||this.b.qc(this.window)||this.b.wb()||this.b.xb(this.S,this.J,this.dvObj)||(this.J.X!=this.Y.Firefox&&this.J.X!=this.Y.IE?this.c.Af():this.J.X==
this.Y.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.c.xc()):window.document.body.getBoundingClientRect||this.c.xc();this.mc=this.c.Zb();this.b.a("ff24e")};this.Sa=function(a,b,c){try{a()}catch(d){try{if(0<this.md){this.md--;var e=this.b.sb(),f=this.b.Wc(b||"unknown caller",c||d);this.R.T(this.ia.protocol+this.ia.domain+this.ia.port+"/"+this.ia.api+"?"+this.U+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+this.Vb+e+"&napr="+f,this.logEvents.errorlevel1)}}catch(g){}}};
return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(b){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||b.cvmSettings||b.billable?(new dv_CustomClientViewAssureService(b)).inViewManager():(new dv_InViewService(b)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var na=[window.$dvbs,window.$dvbsr],Z=0;Z<na.length;Z++){var dvObj=
na[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs628");if(tagObject){var serviceParams=tagObject.services.avs628;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(b){};
